apiVersion: apps/v1

kind: Deployment

metadata:
  name: linux-tweet-app

spec:
  selector:
    matchLabels:
      app: linux-tweet-app
      tier: backend
  
  replicas: 1

  template:
      metadata:
        labels:
          app: linux-tweet-app
          tier: backend

      spec:
        containers:
          - name: linux-tweet-app

            image: plim1025/linux_tweet_app
